#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

# Copies files onto Android devices using SSH. The devices should run the
# “SSHelper” program that provides an SSH server for Android.

set -e
set -u

shopt -s nullglob
shopt -s extglob

# Directories with PDF files that should be copied onto the device.
pdfdirs=(

"$HOME/Dokumente/2012-LaTeX_Kurs"
"$HOME/Dokumente/Anleitungen"
"$HOME/Dokumente/Aufsaetze/Brandon_Patrick_In_Space"
"$HOME/Dokumente/Informationen"
"$HOME/Dokumente/Nachhilfe"
"$HOME/Dokumente/Physik_Dokumente"
"$HOME/Dokumente/Schule/Abizeitung/Abizeitung.pdf"
"$HOME/Dokumente/Spektrum"
"$HOME/Dokumente/Studium/"Modulhandbuch_*.pdf
"$HOME/Dokumente/Studium/astro121"
"$HOME/Dokumente/Studium/astro122"
"$HOME/Dokumente/Studium/EBooks"
"$HOME/Dokumente/Studium/math140"
"$HOME/Dokumente/Studium/math240"
"$HOME/Dokumente/Studium/math340"
"$HOME/Dokumente/Studium/physik220"
"$HOME/Dokumente/Studium/physik312"
"$HOME/Dokumente/Studium/physik321"

)

# Folders where data will build up on the device.
bins=(

"DCIM"
"Download"
"Pictures/Screenshots"
"TODO"

)

# IP addresses where Android devices might be.
ips=(

192.168.0.110		# Frederike
192.168.100.{100..110}	# Home
192.168.43.1		# Hotspot created by phone

)

# Files that should be copied into the ``$HOME`` on the devices.
dotfiles=(

"$HOME/.bashrc"
"$HOME/.vimrc"

)

# Retrives the hostname from the device.
#
# Options:
#   -p PORT         SSH port to use
#   -t TARGET       Target folder
get-hostname() {
	local target
	local tempfile

	while getopts "t:" opt
	do
		case "$opt" in
			t)
				target="$OPTARG"
				;;
		esac
	done

	tempfile="$(mktemp)"

	myrsync -p "$port" "$target/hostname.txt" "$tempfile" &> /dev/null

	cat "$tempfile"
	
	rm -f "$tempfile"
}

# Gathers colorcodes. It will set the variables for use within the program:
# black, blue, cyan, green, orange, burple, red, white and bold, reset.
gather-colorcodes() {
	if [[ -x /usr/bin/tput ]] && tput setaf 1 >&/dev/null
	then
		bold="$(tput bold)"

		black="$(tput setaf 0)"
		blue="$(tput setaf 4)"
		cyan="$(tput setaf 6)"
		green="$(tput setaf 2)"
		orange="$(tput setaf 3)"
		purple="$(tput setaf 5)"
		red="$(tput setaf 1)"
		white="$(tput setaf 7)"

		reset="$(tput sgr0)"
	else
		bold=

		black=
		blue=
		cyan=
		green=
		orange=
		purple=
		red=
		white=

		reset=
	fi
}

# Wrapper for rsync with all the options.
#
# Options:
#   -p PORT         Port for SSH
#
# Positional arguments:
#   OPTIONS         other rsync options and arguments
myrsync() {
	local port

	while getopts "p:" opt
	do
		case "$opt" in
			p)
				port="$OPTARG"
				;;
		esac
	done

	rsync --rsh="ssh -p $port" --progress -hlmrv --size-only --ignore-errors \
		"$@"
}

# Copies a folder with PDFs to the device.
#
# Options:
#   -b BASE         base on the computer
#   -p PORT         Port for SSH
#   -t TARGET       target folder on device
#
# Positional arguments:
#   FROM            folder on the computer
copy-single-pdf-folder() {
	local from
	local frombase
	local target

	while getopts "b:p:t:" opt
	do
		case "$opt" in
			b)
				frombase="$OPTARG"
				;;
			p)
				port="$OPTARG"
				;;
			t)
				target="$OPTARG"
				;;
		esac
	done

	from="$1"
	frombase="${from#/home/*/}"
	target="$target_pdf/${frombase%/*}"

	echo "${cyan}Folder $from to $target${reset}"

	ssh -p "$port" "$ip" "mkdir -p \"${target#*:}\""
	myrsync --delete --include='*.pdf' --include='*/' --exclude='*' \
		"$from" "$target/"

	echo
}

# Moves a given folder to the dropfolder.
#
# Options:
#   -d DROPFOLDER   folder on computer
#   -p PORT         port for SSH
#   -t TARGET       target folder on device
#
# Positional arguments:
#   FOLDER          folder on the remote device
move-to-computer() {
	local dropfolder
	local folder
	local port
	local target

	folder="$1"

	while getopts "d:p:t:" opt
	do
		case "$opt" in
			d)
				dropfolder="$OPTARG"
				;;
			p)
				port="$OPTARG"
				;;
			t)
				target="$OPTARG"
				;;
		esac
	done

	print-heading "move $folder to computer"

	myrsync -p "$port" -b "$target/$folder/" "$dropfolder"
	ssh -p "$port" "$ip" "rm -frv /sdcard/$folder/*"
}

# Prints a colored heading.
#
# Positional arguments
#   TEXT            text to print
print-heading() {
	echo
	echo "${green}$1${reset}"
	echo
}

# Prints a colored “NEXUS” banner.
print-nexus() {
	cat <<<EOF
	│╲   │  ┌──  ${blue}╲  ${red}╱${reset}  │   │  ╱──
	│ ╲  │  │__   ${blue}╲${red}╱${reset}   │   │  ╲__
	│  ╲ │  │     ${orange}╱${green}╲${reset}   │   │     ╲
	│   ╲│  └── ${orange} ╱  ${green}╲${reset}  └───┘   __╱
	EOF
}

# Checks whether the given host is reachable.
#
# Positional arguments:
#   IP              IP address to check
#
# Exit status:
#   the exit status of ping
ping-test() {
	ping -c 1 -w 1 "$1" &> /dev/null
}

# Copies dotfiles to the remote device.
copy-dotfiles() {
	myrsync -p "$port" "${dotfiles[@]}" "$target/"
}

# copies PDF files to the device using ``copy-single-pdf-folder``.
copy-pdffiles() {
	print-heading "copying PDF files to device"

	for pdfdir
	do
		copy-single-pdf-folder -p "$port" "$pdfdir"
	done
}

# Copies the contents of the bins using ``move-to-computer``.
#
# Options:
#   -d DROPFOLDER   folder on computer
#   -p PORT         port for SSH
#   -t TARGET       target folder on device
#
# Positional arguments:
#   BIN ...         bins to empty
copy-bins() {
	local dropfolder
	local folder
	local port
	local target

	folder="$1"

	while getopts "d:p:t:" opt
	do
		case "$opt" in
			d)
				dropfolder="$OPTARG"
				;;
			p)
				port="$OPTARG"
				;;
			t)
				target="$OPTARG"
				;;
		esac
	done

	for bin
	do
		move-to-computer -d "$dropfolder" -p "$port" -t "$target" "$bin"
	done
}

# Copies all the music to the device.
#
# Options:
#   -p PORT         SSH port to use
#
# Positional arguments:
#   TARGET          Target folder
copy-music() {
	local port
	local target_music

	while getopts "p:" opt
	do
		case "$opt" in
			p)
				port="$OPTARG"
				;;
		esac
	done

	target_music="$1"

	print-heading "Copying MP3 files to device"
	myrsync -p "$port" --delete --max-size 15M \
		--force --exclude-from "/home/mu/.config/syncscripts/handy_musik.txt" \
		"/home/mu/.cache/mp3_packer/128/home/mu/Musik/Musik/" "$target_music/"
}

# Gives the user access rights to all the files in the dropfolder. Apparently,
# the files that are copied from the device have their permissions preserved.
# Since the user ID is different, the user who calls this script does not have
# permissions on the files and folders.
#
# Positional arguments:
#   DROPFOLDER      folder on computer
fix-permissions() {
	local dropfolder

	dropfolder="$1"

	print-heading "Fix permissions in $dropfolder"
	find "$dropfolder" -type d -exec chmod u+rwx '{}' \;
	find "$dropfolder" -type f -exec chmod u+rw '{}' \;
}

# Performs the syncing. This functions pretty much calls all other functions.
#
# Positional arguments
#   IP              IP address of the device
sync-device() {
	local dropfolder
	local hostname
	local ip
	local port
	local target
	local target_music
	local target_pdf

	ip="$1"

	if ! ping-test "$ip"
	then
		echo "${red}Device is not reachable. Aborting.${reset}"
		return
	fi

	port="2222"
	target="$ip:/sdcard"
	target_music="$target/Music"
	target_pdf="$target/PDF"

	dropfolder="$HOME/TODO"

	hostname="$(get-hostname -t "$target")"

	echo "${bold}Syncing $hostname @ $ip${reset}"

	copy-bins -d "$dropfolder" -p "$port" -t "$target" "${bins[@]}"
	copy-dotfiles -p "$port" "${dotfiles[@]}"
	copy-pdffiles -p "$port" "${pdfdirs[@]}"
	copy-music -p "$port"

	fix-permissions "$dropfolder"

	backup-status update "$hostname"
}

gather-colorcodes

if [[ -n "${1:-}" ]]
then
	sync-device "$1"
else
	for ip in "${ips[@]}"
	do
		if ! sync-device "$ip"
		then
			echo "Failed."
		fi
	done
fi
