#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u
set -x

shopt -s nullglob

mountpoint="$(mktemp -d)"
dropfolder="$(mktemp -d ~/TODO/android-sync-XXX)"

cleanup() {
    fusermount -u "$mountpoint"
    rmdir "$mountpoint"
    rmdir --ignore-fail-on-non-empty "$dropfolder"
}

trap cleanup EXIT

mtpfs -o allow_other "$mountpoint"

ls "$mountpoint"

sdcard1="$mountpoint/Interner Speicher"
sdcard2="$mountpoint/SD-Karte"

if [[ -d "$sdcard1" ]]
then
    sdcard="$sdcard1"
fi

if [[ -d "$sdcard2" ]]
then
    sdcard="$sdcard2"
fi

ls "$sdcard"

for bin in DCIM Download Locus/export Pictures/Screenshots TODO
do
    ls -l "$sdcard/$bin/"
    mv -v "$sdcard/$bin/"* "$dropfolder/"
done

cd "$HOME"

rsync -rv --files-from <(find /home/mu/Dokumente/Studium -name "*.pdf" -type f | cut -d / -f 4-) . "$sdcard/PDF/"
