#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u
set -x

mountpoint="$(mktemp -d)"
dropfolder="$(mktemp -d ~/TODO/android-sync-XXX)"

mtpfs -o allow_other "$mountpoint"

ls "$mountpoint"

sdcard="$mountpoint/Interner Speicher/"

for bin in DCIM Download Locus/export OpenGPSTracker Pictures/Screenshots TODO
do
    ls "$sdcard/$bin"
done


fusermount -u "$mountpoint"
rmdir "$mountpoint"
rmdir --ignore-fail-on-non-empty "$dropfolder"
