#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

shopt -s nullglob
shopt -s extglob

pdfdirs=(

"$HOME/Dokumente/2012-LaTeX_Kurs"
"$HOME/Dokumente/Anleitungen"
"$HOME/Dokumente/Aufsaetze/Brandon_Patrick_In_Space"
"$HOME/Dokumente/Informationen"
"$HOME/Dokumente/Nachhilfe"
"$HOME/Dokumente/Physik_Dokumente"
"$HOME/Dokumente/Schule/Abizeitung/Abizeitung.pdf"
"$HOME/Dokumente/Spektrum"
"$HOME/Dokumente/Studium/"Modulhandbuch_*.pdf
"$HOME/Dokumente/Studium/EBooks"
"$HOME/Dokumente/Studium/math340"
"$HOME/Dokumente/Studium/physik312"
"$HOME/Dokumente/Studium/physik321"

)

bins=(

DCIM
Download
TODO

)

ips=(

"192.168.100.101"
"192.168.100.106"
"192.168.43.1"

)

dotfiles=(

~/.bashrc
~/.vimrc

)

# Gathers colorcodes. It will set the variables for use within the program:
# black, blue, cyan, green, orange, burple, red, white and bold, reset.
gather-colorcodes() {
	if [[ -x /usr/bin/tput ]] && tput setaf 1 >&/dev/null
	then
		bold="$(tput bold)"

		black="$(tput setaf 0)"
		blue="$(tput setaf 4)"
		cyan="$(tput setaf 6)"
		green="$(tput setaf 2)"
		orange="$(tput setaf 3)"
		purple="$(tput setaf 5)"
		red="$(tput setaf 1)"
		white="$(tput setaf 7)"

		reset="$(tput sgr0)"
	else
		bold=

		black=
		blue=
		cyan=
		green=
		orange=
		purple=
		red=
		white=

		reset=
	fi
}

# Wrapper for rsync with all the options.
#
# :param: A list with more parameters for rsync.
myrsync() {
	rsync --rsh="ssh -p $port" --progress -hlmrv --size-only --ignore-errors \
		"$@"
}

# Copies a folder with PDFs to the device.
#
# :param: Folder to copy.
copypdf() {
	local from="$1"
	local frombase="${from#/home/*/}"
	local target="$target_pdf/${frombase%/*}"

	echo "${cyan}Folder $from to $target${reset}"

	ssh -p "$port" "$ip" "mkdir -p \"${target#*:}\""
	myrsync --delete --include='*.pdf' --include='*/' --exclude='*' \
		"$from" "$target/"

	echo
}

# Moves a given folder to the dropfolder.
#
# :param: Folder on the remote device.
move-to-computer() {
	folder="$1"

	print-heading "move $folder to computer"

	myrsync "$target/$folder/" "$dropfolder"
	ssh -p 2222 "$ip" "rm -frv /sdcard/$folder/*"
}

# Prints a colored heading.
#
# :param: Heading text.
print-heading() {
	echo
	echo "${green}$1${reset}"
	echo
}

# Prints a colored “NEXUS” banner.
print-nexus() {
	cat <<<EOF
	│╲   │  ┌──  ${blue}╲  ${red}╱${reset}  │   │  ╱──
	│ ╲  │  │__   ${blue}╲${red}╱${reset}   │   │  ╲__
	│  ╲ │  │     ${orange}╱${green}╲${reset}   │   │     ╲
	│   ╲│  └── ${orange} ╱  ${green}╲${reset}  └───┘   __╱
	EOF
}

# Checks whether the given host is reachable.
#
# :returns: the exit status of ping
ping-test() {
	ping -c 1 -w 1 "$ip" &> /dev/null
}

# Copies dotfiles to the remote device.
copy-dotfiles() {
	myrsync "${dotfiles[@]}" \
		"$ip:/data/data/com.spartacusrex.spartacuside/files/"

	myrsync "${dotfiles[@]}" \
		"$target/"
}

# copies PDF files to the device using ``copypdf``.
copy-pdffiles() {
	print-heading "copying PDF files to device"
	for pdfdir in "${pdfdirs[@]}"
	do
		copypdf "$pdfdir"
	done
}

# Copies the contents of the bins using ``move-to-computer``.
copy-bins() {
	for bin in "${bins[@]}"
	do
		move-to-computer "$bin"
	done
}

# Copies all the music to the device.
copy-music() {
	print-heading "Copying MP3 files to device"
	myrsync --delete --max-size 15M \
		--force --exclude-from "/home/mu/.config/syncscripts/handy_musik.txt" \
		"/home/mu/.cache/mp3_packer/128/home/mu/Musik/Musik/" "$target_music/"
}

# Performs the syncing. This functions pretty much calls all other functions.
sync-device() {
	echo "${bold}Syncing $ip${reset}"

	if ! ping-test
	then
		echo "${red}Device is not reachable. Aborting.${reset}"
		return
	fi

	port="2222"
	target="$ip:/sdcard"
	target_music="$target/Music"
	target_pdf="$target/PDF"

	dropfolder="$HOME/TODO"

	copy-bins
	copy-dotfiles
	copy-music
	copy-pdffiles

	backup-status update "$target"
}

gather-colorcodes

for ip in "${ips[@]}"
do
	sync-device
done
