#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -u
set -e

target=/media/Gamma/Backup
if [ -d "$target" ]
then
	time rsync -avhE --delete \
		--exclude-from ~/.syncscripts/gamma_exclude.txt /home/mu "$target/home/"
	time rsync -avhE --delete \
		--exclude-from ~/.syncscripts/gamma_exclude.txt /etc "$target/"

	if [[ -d "$HOME/.nag"]]
	then
		touch "$HOME/.nag/Backup to Gamma"
	fi

else
	echo -e "ERROR: $target is not mounted"
fi
