#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

ping -c 1 speedport.ip

cleanup() {
	# Release the mounted FTP
	if [[ -d "$tempdir" ]]
	then
		fusermount -u "$tempdir"
		rmdir -- "$tempdir"
	fi
}

trap cleanup EXIT
trap cleanup ERR

# Create a mountpoint for the FTP.
tempdir=$(mktemp -d)
chgrp fuse -- "$tempdir"
chmod 700 -- "$tempdir"

# Mount the FTP
curlftpfs "speedport.ip" "$tempdir"


# Copy all the new data into the current directory
mkdir -p "$tempdir/backup-martin/"
rsync -avE --delete -- "$HOME/Dokumente/Listen/Hauptliste.kdb" "$tempdir/backup-martin/"

echo "Backup speedport.ip is done."

backup-status update "speedport.ip"
