#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

import optparse
import subprocess
import os

backups = {
    "Eta": "/media/Eta/Backup",
    "Gamma": "/media/Gamma/Backup",
    "Sigma": "/media/Sigma/Backup",
    "USB-Eins": "/media/USB-Eins",
    "USB-Zwei": "/media/USB-Zwei"
}

def backup(name, target):
    includesfile = os.path.expanduser("~/.config/syncscripts/"+name+".include.txt")
    excludesfile = os.path.expanduser("~/.config/syncscripts/"+name+".exclude.txt")

    if os.path.exists(includesfile):
        with open(includesfile) as h:
            for include in h:
                include = include.strip()

                print "Backup %s -- %s" % (name, include)
                destdir = target+os.path.dirname(include)

                if os.path.exists(excludesfile):
                    exclude_arg = ["--exclude-from", excludesfile]
                else:
                    exclude_arg = []

                status = subprocess.call(["rsync", "-avhE", "--delete"] + exclude_arg + ["--", include, destdir])

                if status == 0:
                    subprocess.call(["backup-status", "update", name])


def main():
    for name, target in backups.items():
        if os.path.exists(target):
            backup(name, target)


if __name__ == "__main__":
	main()
