#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2011-2013 Martin Ueding <dev@martin-ueding.de>

"""
Traverses through the external drives and updates the backup on them.
"""

import colorcodes
import optparse
import os
import subprocess

__docformat__ = "restructuredtext en"

data_partitions = [
    "Gamma",
    "MU-1-466G-data",
    "MU-3-466G-data",
]

info_partitions = [
    "MU-1-466G-info",
    "MU-3-466G-info",
]

infofiles = [
    os.path.expanduser("~/Dokumente/Listen/Hauptliste.kdb"),
    os.path.expanduser("~/Installer/Sicherheit/KeePass-1.15-Setup.exe"),
    os.path.expanduser("~/Installer/Sicherheit/KeePassX-0.4.0.dmg"),
]

_c = colorcodes.Colorcodes()

def backup_data(name):
    """
    Creates a backup to ``target``.

    :param name: Name of this backup.
    :type name: str
    :param target: Target directory.
    :type target: str
    """
    excludesfile = os.path.expanduser("~/.config/backup-scripts/full.exclude.txt")

    source = os.path.expanduser("~")

    target = os.path.join("/media/mu", '{}'.format(name))
    heading = "Backup {}".format(name)
    print(_c.bold + heading + _c.reset)
    print(_c.bold + ("="*len(heading)) + _c.reset)

    if not os.path.isdir(target):
        print(_c.red + "Target {} does not exist.".format(target) + _c.reset)
        return

    destdir = "{}/home/".format(target)

    if os.path.exists(excludesfile):
        exclude_arg = ["--exclude-from", excludesfile]
    else:
        exclude_arg = []

    if not os.path.isdir(destdir):
        os.makedirs(destdir)

    command = ["rsync", "-avhE", "--delete", "--delete-excluded"] + exclude_arg + ["--", source, destdir]
    print(command)

    try:
        subprocess.check_call(command)
    except subprocess.CalledProcessError as e:
        print(e)
    else:
        subprocess.call(["backup-status", "update", "{}".format(name)])

def backup_info(name):
    target = "/media/mu/{}/info/".format(name)

    if not os.path.isdir(target):
        print(_c.red + "Target {} does not exist.".format(target) + _c.reset)
        return

    command = ["rsync", "-avhE", "--delete", "--"] + infofiles + [target]

    try:
        subprocess.check_call(command)
    except subprocess.CalledProcessError as e:
        print(e)
    else:
        subprocess.call(["backup-status", "update", "{}".format(name)])

def main():
    for name in data_partitions:
        backup_data(name)

    for name in info_partitions:
        backup_info(name)

if __name__ == "__main__":
	main()
