#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

shopt -s extglob

cd "$HOME"

rsync="rsync -aEhv --delete"
target="chaos"

$rsync .vim "$target:"
$rsync debuild "$target:"
$rsync Dokumente/Listen "$target:Dokumente/"
$rsync Dokumente/Studium/*+([0-9]) "$target:Dokumente/Studium/"
$rsync Projekte "$target:"
$rsync rpmbuild "$target:"
$rsync Vorlagen "$target:"

if type backup-status &> /dev/null
then
	backup-status --update chaos --direction to
fi
