#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -u
set -e

target=/media/Sigma/Backup/

# Check whether the target directory is actually available.
if [ ! -d "$target" ]
then
	echo -e "ERROR: $target is not mounted"
	exit 1
fi

time rsync -avhE --delete \
	--exclude-from ~/.syncscripts/gamma_exclude.txt /home/mu/ "$target"
