#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -u
set -e

target=/media/Gamma/Backup
if [ ! -d "$target" ]
then
	echo -e "ERROR: $target is not mounted"
	exit 1
fi

time rsync -avhE --delete \
	--exclude-from ~/.syncscripts/gamma_exclude.txt /home/mu "$target/home/"
time rsync -avhE --delete \
	--exclude-from ~/.syncscripts/gamma_exclude.txt /etc "$target/"

if which kdialog > /dev/null
then
	kdialog --passivepopup 'Backup Gamma done.' 3
fi
