#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# Copies music to the phone and moves pictures and audio notes to a given
# folder on the computer. The music is shrinked to 128 kBit/s to save space on
# the phone using the mp3_packer.

set -e
set -u

target="/media/THETA"
dropfolder="$HOME/TODO/"

mp3_packer="$HOME/Branches/mp3_packer/mp3_packer.py"


if which ffmpeg > /dev/null
then
	"$mp3_packer" "$HOME/Musik/Musik/"
fi


if [[ ! -d "$target" ]]
then
	echo -e "ERROR: $target is not mounted"
	exit 1
fi

if ! touch "$target/rw-test"
then
	echo "$target is writeable"
	exit 1
else
	rm "$target/rw-test"
fi


# Delete all empty files that cause trouble from the target's MP3 folder.
find "$target/MP3" -size 0 -delete

time rsync --max-size 15M -vr --size-only --delete --ignore-errors \
	--force --exclude-from "/home/mu/.syncscripts/handy_musik.txt" \
	"/home/mu/.mp3_packer/128/home/mu/Musik/Musik" "$target/MP3/"

# move pictures
find "$target/DCIM/" -type f -exec mv '{}' "$dropfolder" \;

# move audio notes
for i in "$target/MSSEMC/Media Files/audio/"*.amr
do
	mv -v "$i" "$dropfolder/$(uuidgen).amr"
done

# save my password list
passwordlist="$HOME/Dokumente/Listen/Hauptliste.kdb"
if [[ -f "$passwordlist" ]]
then
	cp -v "$passwordlist" "$target/"
fi
