#!/bin/bash
# Copyright (c) 2011-2012 Martin Ueding <dev@martin-ueding.de>

# Copies music to the phone and moves pictures and audio notes to a given
# folder on the computer.
#
# The music is shrinked to 128 kBit/s to save space on the phone using the
# mp3_packer.

set -e
set -u

shopt -s nullglob

target="/media/THETA"
dropfolder="$HOME/TODO/"

if which ffmpeg > /dev/null
then
	mp3-packer "$HOME/Musik/Musik/"
else
	echo "Warning: Do not call mp3-packer since ffmpeg is missing."
fi


if [[ ! -d "$target" ]]
then
	echo -e "Error: $target is not mounted"
	exit 1
fi

if ! touch "$target/rw-test"
then
	echo "$target is writeable"
	exit 1
else
	rm "$target/rw-test"
fi


# Delete all empty files that cause trouble from the target's MP3 folder.
find "$target/MP3" -size 0 -delete

time rsync --max-size 15M -vr --size-only --delete --ignore-errors \
	--force --exclude-from "/home/mu/.config/syncscripts/handy_musik.txt" \
	"/home/mu/.cache/mp3_packer/128/home/mu/Musik/Musik" "$target/MP3/"

# Move pictures.
rename -v 's/JPG$/jpg/' "$target"/DCIM/*/*.JPG foobar
find "$target/DCIM/" -type f -exec mv '{}' "$dropfolder" \;

# Move audio notes.
for i in "$target/MSSEMC/Media Files/audio/"*.amr
do
	mv -v "$i" "$dropfolder/$(uuidgen).amr"
done

# Backup my password list.
passwordlist="$HOME/Dokumente/Listen/Hauptliste.kdb"
if [[ -f "$passwordlist" ]]
then
	cp -v "$passwordlist" "$target/"
fi

backup-status update "$target"
