#!/bin/bash
# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

if (( $# != 2 ))
then
    echo "Usage: $0 DEVICE LABEL"
    exit 1
fi

cleanup() {
    set +e
    umount /mnt
    cryptsetup luksClose provision
}

trap cleanup EXIT

cryptsetup --verbose --verify-passphrase luksFormat "$1"

cryptsetup luksOpen "$1" provision

mkfs.btrfs --label "$2" /dev/mapper/provision

mount /dev/mapper/provision /mnt

mkdir -p /mnt/home/mu
chown mu:mu /mnt/home/mu
